// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recorder.proto

package recorder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateRequest) Reset()         { *m = StateRequest{} }
func (m *StateRequest) String() string { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()    {}
func (*StateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b063ffe85a4e6395, []int{0}
}

func (m *StateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageState_StateRequest.Unmarshal(m, b)
}
func (m *StateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageState_StateRequest.Marshal(b, m, deterministic)
}
func (m *StateRequest) XXX_Merge(src proto.Message) {
	xxx_messageState_StateRequest.Merge(m, src)
}
func (m *StateRequest) XXX_Size() int {
	return xxx_messageState_StateRequest.Size(m)
}
func (m *StateRequest) XXX_DiscardUnknown() {
	xxx_messageState_StateRequest.DiscardUnknown(m)
}

var xxx_messageState_StateRequest proto.InternalMessageInfo

type StateResponse struct {
	Devices              []string `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateResponse) Reset()         { *m = StateResponse{} }
func (m *StateResponse) String() string { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()    {}
func (*StateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b063ffe85a4e6395, []int{1}
}

func (m *StateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageState_StateResponse.Unmarshal(m, b)
}
func (m *StateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageState_StateResponse.Marshal(b, m, deterministic)
}
func (m *StateResponse) XXX_Merge(src proto.Message) {
	xxx_messageState_StateResponse.Merge(m, src)
}
func (m *StateResponse) XXX_Size() int {
	return xxx_messageState_StateResponse.Size(m)
}
func (m *StateResponse) XXX_DiscardUnknown() {
	xxx_messageState_StateResponse.DiscardUnknown(m)
}

var xxx_messageState_StateResponse proto.InternalMessageInfo

func (m *StateResponse) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

type StartSendRequest struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Channels             uint32   `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	Rate                 uint32   `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	DestAddr             string   `protobuf:"bytes,4,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSendRequest) Reset()         { *m = StartSendRequest{} }
func (m *StartSendRequest) String() string { return proto.CompactTextString(m) }
func (*StartSendRequest) ProtoMessage()    {}
func (*StartSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b063ffe85a4e6395, []int{2}
}

func (m *StartSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageState_StartSendRequest.Unmarshal(m, b)
}
func (m *StartSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageState_StartSendRequest.Marshal(b, m, deterministic)
}
func (m *StartSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageState_StartSendRequest.Merge(m, src)
}
func (m *StartSendRequest) XXX_Size() int {
	return xxx_messageState_StartSendRequest.Size(m)
}
func (m *StartSendRequest) XXX_DiscardUnknown() {
	xxx_messageState_StartSendRequest.DiscardUnknown(m)
}

var xxx_messageState_StartSendRequest proto.InternalMessageInfo

func (m *StartSendRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *StartSendRequest) GetChannels() uint32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

func (m *StartSendRequest) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *StartSendRequest) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

type StartSendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSendResponse) Reset()         { *m = StartSendResponse{} }
func (m *StartSendResponse) String() string { return proto.CompactTextString(m) }
func (*StartSendResponse) ProtoMessage()    {}
func (*StartSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b063ffe85a4e6395, []int{3}
}

func (m *StartSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageState_StartSendResponse.Unmarshal(m, b)
}
func (m *StartSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageState_StartSendResponse.Marshal(b, m, deterministic)
}
func (m *StartSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageState_StartSendResponse.Merge(m, src)
}
func (m *StartSendResponse) XXX_Size() int {
	return xxx_messageState_StartSendResponse.Size(m)
}
func (m *StartSendResponse) XXX_DiscardUnknown() {
	xxx_messageState_StartSendResponse.DiscardUnknown(m)
}

var xxx_messageState_StartSendResponse proto.InternalMessageInfo

type StopSendRequest struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSendRequest) Reset()         { *m = StopSendRequest{} }
func (m *StopSendRequest) String() string { return proto.CompactTextString(m) }
func (*StopSendRequest) ProtoMessage()    {}
func (*StopSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b063ffe85a4e6395, []int{4}
}

func (m *StopSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageState_StopSendRequest.Unmarshal(m, b)
}
func (m *StopSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageState_StopSendRequest.Marshal(b, m, deterministic)
}
func (m *StopSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageState_StopSendRequest.Merge(m, src)
}
func (m *StopSendRequest) XXX_Size() int {
	return xxx_messageState_StopSendRequest.Size(m)
}
func (m *StopSendRequest) XXX_DiscardUnknown() {
	xxx_messageState_StopSendRequest.DiscardUnknown(m)
}

var xxx_messageState_StopSendRequest proto.InternalMessageInfo

func (m *StopSendRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type StopSendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSendResponse) Reset()         { *m = StopSendResponse{} }
func (m *StopSendResponse) String() string { return proto.CompactTextString(m) }
func (*StopSendResponse) ProtoMessage()    {}
func (*StopSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b063ffe85a4e6395, []int{5}
}

func (m *StopSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageState_StopSendResponse.Unmarshal(m, b)
}
func (m *StopSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageState_StopSendResponse.Marshal(b, m, deterministic)
}
func (m *StopSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageState_StopSendResponse.Merge(m, src)
}
func (m *StopSendResponse) XXX_Size() int {
	return xxx_messageState_StopSendResponse.Size(m)
}
func (m *StopSendResponse) XXX_DiscardUnknown() {
	xxx_messageState_StopSendResponse.DiscardUnknown(m)
}

var xxx_messageState_StopSendResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StateRequest)(nil), "recorder.StateRequest")
	proto.RegisterType((*StateResponse)(nil), "recorder.StateResponse")
	proto.RegisterType((*StartSendRequest)(nil), "recorder.StartSendRequest")
	proto.RegisterType((*StartSendResponse)(nil), "recorder.StartSendResponse")
	proto.RegisterType((*StopSendRequest)(nil), "recorder.StopSendRequest")
	proto.RegisterType((*StopSendResponse)(nil), "recorder.StopSendResponse")
}

func init() { proto.RegisterFile("recorder.proto", fileDescriptor_b063ffe85a4e6395) }

var fileDescriptor_b063ffe85a4e6395 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xbb, 0x4e, 0xc4, 0x30,
	0x10, 0xc4, 0x5c, 0x80, 0xdc, 0xc2, 0xf1, 0x58, 0x04, 0x32, 0x46, 0x42, 0x91, 0xab, 0x54, 0x27,
	0x01, 0x05, 0x25, 0x82, 0x8e, 0x86, 0xc2, 0xf9, 0x82, 0x10, 0x2f, 0x02, 0x09, 0xec, 0x60, 0x1b,
	0x4a, 0xbe, 0x8f, 0xcf, 0x42, 0x71, 0x1e, 0x84, 0x53, 0x9a, 0xeb, 0x32, 0x3b, 0xb3, 0x93, 0xd9,
	0x31, 0xec, 0x3b, 0xaa, 0xac, 0xd3, 0xe4, 0x96, 0xb5, 0xb3, 0xc1, 0x62, 0xda, 0x63, 0xb9, 0x80,
	0xdd, 0x07, 0xf3, 0x6c, 0x15, 0x7d, 0x7c, 0x92, 0x0f, 0x32, 0x87, 0xbd, 0x16, 0xfa, 0xda, 0x1a,
	0x4f, 0xc8, 0x61, 0x47, 0xd3, 0xd7, 0x6b, 0x45, 0x9e, 0xb3, 0x6c, 0x96, 0xcf, 0x55, 0x0f, 0xe5,
	0x37, 0x1c, 0x16, 0xa1, 0x74, 0xa1, 0x20, 0xa3, 0xbb, 0x6d, 0xbc, 0x00, 0x68, 0xe9, 0xc7, 0xf2,
	0x9d, 0x38, 0xcb, 0x58, 0x3e, 0x57, 0xa3, 0x09, 0x0a, 0x48, 0xab, 0x97, 0xd2, 0x18, 0x7a, 0xf3,
	0x7c, 0x33, 0x63, 0xf9, 0x42, 0x0d, 0x18, 0x11, 0x12, 0x57, 0x06, 0xe2, 0xb3, 0x38, 0x8f, 0xdf,
	0x8d, 0x5e, 0x93, 0x0f, 0x77, 0x5a, 0x3b, 0x9e, 0x44, 0xb7, 0x01, 0xcb, 0x63, 0x38, 0x1a, 0xfd,
	0xbf, 0x8d, 0x2b, 0x2f, 0xe1, 0xa0, 0x08, 0xb6, 0x5e, 0x23, 0x93, 0xc4, 0xe6, 0x8e, 0x7e, 0xa5,
	0xb5, 0xb9, 0xfa, 0x61, 0x90, 0xaa, 0xae, 0x21, 0xbc, 0x81, 0xa4, 0xa9, 0x04, 0x4f, 0x96, 0x43,
	0x89, 0xa3, 0xc6, 0xc4, 0xe9, 0xea, 0xb8, 0x8b, 0xb2, 0x81, 0xf7, 0xb0, 0x15, 0x13, 0xa2, 0xf8,
	0x93, 0xac, 0x56, 0x26, 0xce, 0x27, 0xb9, 0xc1, 0xe3, 0x16, 0x92, 0x26, 0x1d, 0x9e, 0x8d, 0x65,
	0xff, 0x0e, 0x14, 0x62, 0x8a, 0xea, 0x0d, 0x9e, 0xb6, 0xe3, 0x83, 0x5f, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xc7, 0x1b, 0x49, 0x00, 0x02, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecorderClient is the client API for Recorder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecorderClient interface {
	// State return receiving ports, storages and busy device
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	// Start record from deviceName and send audio on destAddr
	Start(ctx context.Context, in *StartSendRequest, opts ...grpc.CallOption) (*StartSendResponse, error)
	// Stop record from deviceName
	Stop(ctx context.Context, in *StopSendRequest, opts ...grpc.CallOption) (*StopSendResponse, error)
}

type recorderClient struct {
	cc *grpc.ClientConn
}

func NewRecorderClient(cc *grpc.ClientConn) RecorderClient {
	return &recorderClient{cc}
}

func (c *recorderClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, "/recorder.Recorder/State", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recorderClient) Start(ctx context.Context, in *StartSendRequest, opts ...grpc.CallOption) (*StartSendResponse, error) {
	out := new(StartSendResponse)
	err := c.cc.Invoke(ctx, "/recorder.Recorder/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recorderClient) Stop(ctx context.Context, in *StopSendRequest, opts ...grpc.CallOption) (*StopSendResponse, error) {
	out := new(StopSendResponse)
	err := c.cc.Invoke(ctx, "/recorder.Recorder/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecorderServer is the server API for Recorder service.
type RecorderServer interface {
	// State return receiving ports, storages and busy device
	State(context.Context, *StateRequest) (*StateResponse, error)
	// Start record from deviceName and send audio on destAddr
	Start(context.Context, *StartSendRequest) (*StartSendResponse, error)
	// Stop record from deviceName
	Stop(context.Context, *StopSendRequest) (*StopSendResponse, error)
}

// UnimplementedRecorderServer can be embedded to have forward compatible implementations.
type UnimplementedRecorderServer struct {
}

func (*UnimplementedRecorderServer) State(ctx context.Context, req *StateRequest) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method State not implemented")
}
func (*UnimplementedRecorderServer) Start(ctx context.Context, req *StartSendRequest) (*StartSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedRecorderServer) Stop(ctx context.Context, req *StopSendRequest) (*StopSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

func RegisterRecorderServer(s *grpc.Server, srv RecorderServer) {
	s.RegisterService(&_Recorder_serviceDesc, srv)
}

func _Recorder_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServer).State(ctx, in)
	}
	State := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recorder.Recorder/State",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServer).State(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, State, handler)
}

func _Recorder_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServer).Start(ctx, in)
	}
	State := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recorder.Recorder/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServer).Start(ctx, req.(*StartSendRequest))
	}
	return interceptor(ctx, in, State, handler)
}

func _Recorder_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecorderServer).Stop(ctx, in)
	}
	State := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recorder.Recorder/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecorderServer).Stop(ctx, req.(*StopSendRequest))
	}
	return interceptor(ctx, in, State, handler)
}

var _Recorder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recorder.Recorder",
	HandlerType: (*RecorderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "State",
			Handler:    _Recorder_State_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Recorder_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Recorder_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recorder.proto",
}
