// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package player

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartReceiveRequest struct {
	Port                 string                `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	StorageUUID          *wrappers.StringValue `protobuf:"bytes,2,opt,name=storageUUID,proto3" json:"storageUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StartReceiveRequest) Reset()         { *m = StartReceiveRequest{} }
func (m *StartReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*StartReceiveRequest) ProtoMessage()    {}
func (*StartReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *StartReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReceiveRequest.Unmarshal(m, b)
}
func (m *StartReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReceiveRequest.Marshal(b, m, deterministic)
}
func (m *StartReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReceiveRequest.Merge(m, src)
}
func (m *StartReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_StartReceiveRequest.Size(m)
}
func (m *StartReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartReceiveRequest proto.InternalMessageInfo

func (m *StartReceiveRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *StartReceiveRequest) GetStorageUUID() *wrappers.StringValue {
	if m != nil {
		return m.StorageUUID
	}
	return nil
}

type StartReceiveResponse struct {
	StorageUUID          string   `protobuf:"bytes,1,opt,name=storageUUID,proto3" json:"storageUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReceiveResponse) Reset()         { *m = StartReceiveResponse{} }
func (m *StartReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*StartReceiveResponse) ProtoMessage()    {}
func (*StartReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *StartReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReceiveResponse.Unmarshal(m, b)
}
func (m *StartReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReceiveResponse.Marshal(b, m, deterministic)
}
func (m *StartReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReceiveResponse.Merge(m, src)
}
func (m *StartReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_StartReceiveResponse.Size(m)
}
func (m *StartReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartReceiveResponse proto.InternalMessageInfo

func (m *StartReceiveResponse) GetStorageUUID() string {
	if m != nil {
		return m.StorageUUID
	}
	return ""
}

type StopReceiveRequest struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReceiveRequest) Reset()         { *m = StopReceiveRequest{} }
func (m *StopReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*StopReceiveRequest) ProtoMessage()    {}
func (*StopReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}

func (m *StopReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReceiveRequest.Unmarshal(m, b)
}
func (m *StopReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReceiveRequest.Marshal(b, m, deterministic)
}
func (m *StopReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReceiveRequest.Merge(m, src)
}
func (m *StopReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_StopReceiveRequest.Size(m)
}
func (m *StopReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopReceiveRequest proto.InternalMessageInfo

func (m *StopReceiveRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type StopReceiveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReceiveResponse) Reset()         { *m = StopReceiveResponse{} }
func (m *StopReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*StopReceiveResponse) ProtoMessage()    {}
func (*StopReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}

func (m *StopReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReceiveResponse.Unmarshal(m, b)
}
func (m *StopReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReceiveResponse.Marshal(b, m, deterministic)
}
func (m *StopReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReceiveResponse.Merge(m, src)
}
func (m *StopReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_StopReceiveResponse.Size(m)
}
func (m *StopReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopReceiveResponse proto.InternalMessageInfo

type StartPlayRequest struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Channels             uint32   `protobuf:"varint,2,opt,name=channels,proto3" json:"channels,omitempty"`
	Rate                 uint32   `protobuf:"varint,3,opt,name=rate,proto3" json:"rate,omitempty"`
	StorageUUID          string   `protobuf:"bytes,4,opt,name=storageUUID,proto3" json:"storageUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartPlayRequest) Reset()         { *m = StartPlayRequest{} }
func (m *StartPlayRequest) String() string { return proto.CompactTextString(m) }
func (*StartPlayRequest) ProtoMessage()    {}
func (*StartPlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}

func (m *StartPlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPlayRequest.Unmarshal(m, b)
}
func (m *StartPlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPlayRequest.Marshal(b, m, deterministic)
}
func (m *StartPlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPlayRequest.Merge(m, src)
}
func (m *StartPlayRequest) XXX_Size() int {
	return xxx_messageInfo_StartPlayRequest.Size(m)
}
func (m *StartPlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartPlayRequest proto.InternalMessageInfo

func (m *StartPlayRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *StartPlayRequest) GetChannels() uint32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

func (m *StartPlayRequest) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *StartPlayRequest) GetStorageUUID() string {
	if m != nil {
		return m.StorageUUID
	}
	return ""
}

type StartPlayResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartPlayResponse) Reset()         { *m = StartPlayResponse{} }
func (m *StartPlayResponse) String() string { return proto.CompactTextString(m) }
func (*StartPlayResponse) ProtoMessage()    {}
func (*StartPlayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{5}
}

func (m *StartPlayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPlayResponse.Unmarshal(m, b)
}
func (m *StartPlayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPlayResponse.Marshal(b, m, deterministic)
}
func (m *StartPlayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPlayResponse.Merge(m, src)
}
func (m *StartPlayResponse) XXX_Size() int {
	return xxx_messageInfo_StartPlayResponse.Size(m)
}
func (m *StartPlayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPlayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartPlayResponse proto.InternalMessageInfo

type StopPlayRequest struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopPlayRequest) Reset()         { *m = StopPlayRequest{} }
func (m *StopPlayRequest) String() string { return proto.CompactTextString(m) }
func (*StopPlayRequest) ProtoMessage()    {}
func (*StopPlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{6}
}

func (m *StopPlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPlayRequest.Unmarshal(m, b)
}
func (m *StopPlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPlayRequest.Marshal(b, m, deterministic)
}
func (m *StopPlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPlayRequest.Merge(m, src)
}
func (m *StopPlayRequest) XXX_Size() int {
	return xxx_messageInfo_StopPlayRequest.Size(m)
}
func (m *StopPlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopPlayRequest proto.InternalMessageInfo

func (m *StopPlayRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type StopPlayResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopPlayResponse) Reset()         { *m = StopPlayResponse{} }
func (m *StopPlayResponse) String() string { return proto.CompactTextString(m) }
func (*StopPlayResponse) ProtoMessage()    {}
func (*StopPlayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{7}
}

func (m *StopPlayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPlayResponse.Unmarshal(m, b)
}
func (m *StopPlayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPlayResponse.Marshal(b, m, deterministic)
}
func (m *StopPlayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPlayResponse.Merge(m, src)
}
func (m *StopPlayResponse) XXX_Size() int {
	return xxx_messageInfo_StopPlayResponse.Size(m)
}
func (m *StopPlayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPlayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopPlayResponse proto.InternalMessageInfo

type ClearStorageRequest struct {
	StorageUUID          string   `protobuf:"bytes,1,opt,name=storageUUID,proto3" json:"storageUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearStorageRequest) Reset()         { *m = ClearStorageRequest{} }
func (m *ClearStorageRequest) String() string { return proto.CompactTextString(m) }
func (*ClearStorageRequest) ProtoMessage()    {}
func (*ClearStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{8}
}

func (m *ClearStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearStorageRequest.Unmarshal(m, b)
}
func (m *ClearStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearStorageRequest.Marshal(b, m, deterministic)
}
func (m *ClearStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearStorageRequest.Merge(m, src)
}
func (m *ClearStorageRequest) XXX_Size() int {
	return xxx_messageInfo_ClearStorageRequest.Size(m)
}
func (m *ClearStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearStorageRequest proto.InternalMessageInfo

func (m *ClearStorageRequest) GetStorageUUID() string {
	if m != nil {
		return m.StorageUUID
	}
	return ""
}

type ClearStorageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearStorageResponse) Reset()         { *m = ClearStorageResponse{} }
func (m *ClearStorageResponse) String() string { return proto.CompactTextString(m) }
func (*ClearStorageResponse) ProtoMessage()    {}
func (*ClearStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{9}
}

func (m *ClearStorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearStorageResponse.Unmarshal(m, b)
}
func (m *ClearStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearStorageResponse.Marshal(b, m, deterministic)
}
func (m *ClearStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearStorageResponse.Merge(m, src)
}
func (m *ClearStorageResponse) XXX_Size() int {
	return xxx_messageInfo_ClearStorageResponse.Size(m)
}
func (m *ClearStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearStorageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartReceiveRequest)(nil), "player.StartReceiveRequest")
	proto.RegisterType((*StartReceiveResponse)(nil), "player.StartReceiveResponse")
	proto.RegisterType((*StopReceiveRequest)(nil), "player.StopReceiveRequest")
	proto.RegisterType((*StopReceiveResponse)(nil), "player.StopReceiveResponse")
	proto.RegisterType((*StartPlayRequest)(nil), "player.StartPlayRequest")
	proto.RegisterType((*StartPlayResponse)(nil), "player.StartPlayResponse")
	proto.RegisterType((*StopPlayRequest)(nil), "player.StopPlayRequest")
	proto.RegisterType((*StopPlayResponse)(nil), "player.StopPlayResponse")
	proto.RegisterType((*ClearStorageRequest)(nil), "player.ClearStorageRequest")
	proto.RegisterType((*ClearStorageResponse)(nil), "player.ClearStorageResponse")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0xd4, 0x42, 0xed, 0x40, 0xd5, 0x76, 0xa1, 0xad, 0x6b, 0x10, 0x42, 0x3e, 0x71, 0x32,
	0x2a, 0x39, 0x24, 0x52, 0x94, 0x5c, 0x92, 0x43, 0x22, 0xa4, 0x08, 0xd9, 0x22, 0xf7, 0x85, 0x4c,
	0x1c, 0x4b, 0x8e, 0x77, 0xb3, 0x5e, 0x88, 0xb8, 0xe7, 0x61, 0xf3, 0x18, 0x91, 0xd7, 0x3f, 0xac,
	0xc1, 0x12, 0xca, 0xcd, 0xbb, 0x33, 0xdf, 0xcf, 0x7c, 0x3b, 0x86, 0x0e, 0x8f, 0xe8, 0x16, 0x85,
	0xcb, 0x05, 0x93, 0x8c, 0xb4, 0xb2, 0x93, 0x3d, 0x0c, 0x18, 0x0b, 0x22, 0x9c, 0xa8, 0xdb, 0xe5,
	0xfa, 0x71, 0xf2, 0x2a, 0x28, 0xe7, 0x28, 0x92, 0xac, 0xcf, 0x09, 0xa1, 0xeb, 0x4b, 0x2a, 0xa4,
	0x87, 0x2b, 0x0c, 0x37, 0xe8, 0xe1, 0xcb, 0x1a, 0x13, 0x49, 0x08, 0x98, 0x9c, 0x09, 0x69, 0x19,
	0x23, 0x63, 0xfc, 0xcd, 0x53, 0xdf, 0xe4, 0x12, 0xda, 0x89, 0x64, 0x82, 0x06, 0xb8, 0x58, 0xdc,
	0x5e, 0x5b, 0xcd, 0x91, 0x31, 0x6e, 0x4f, 0x07, 0x6e, 0x26, 0xe0, 0x16, 0x02, 0xae, 0x2f, 0x45,
	0x18, 0x07, 0xf7, 0x34, 0x5a, 0xa3, 0xa7, 0x03, 0x9c, 0x33, 0xe8, 0x55, 0xa5, 0x12, 0xce, 0xe2,
	0x04, 0xc9, 0xa8, 0xca, 0x9b, 0x49, 0x56, 0x90, 0x63, 0x20, 0xbe, 0x64, 0xfc, 0xb8, 0x47, 0xe7,
	0x77, 0x3a, 0x8e, 0xd6, 0x99, 0x49, 0x38, 0x6f, 0x06, 0xfc, 0x54, 0xda, 0xf3, 0x88, 0x6e, 0x0b,
	0xfc, 0x10, 0xe0, 0x01, 0x37, 0xe1, 0x0a, 0xef, 0xe8, 0x33, 0xe6, 0x2c, 0xda, 0x0d, 0xb1, 0xe1,
	0xeb, 0xea, 0x89, 0xc6, 0x31, 0x46, 0x89, 0x1a, 0xf6, 0xbb, 0x57, 0x9e, 0x53, 0x6d, 0x41, 0x25,
	0x5a, 0x5f, 0xd4, 0xbd, 0xfa, 0xde, 0x9f, 0xc3, 0x3c, 0x9c, 0xa3, 0x0b, 0xbf, 0x34, 0x17, 0xb9,
	0xb7, 0xff, 0xf0, 0x23, 0xb5, 0xfc, 0x09, 0x67, 0x0e, 0x49, 0xa7, 0x29, 0x20, 0x39, 0xcd, 0x29,
	0x74, 0xaf, 0x22, 0xa4, 0xc2, 0xcf, 0xf4, 0x0a, 0xaa, 0xe3, 0xe1, 0xfe, 0x81, 0x5e, 0x15, 0x98,
	0x11, 0x4e, 0xdf, 0x9b, 0xd0, 0x9a, 0xab, 0x25, 0x22, 0x33, 0xe8, 0xe4, 0x89, 0x2a, 0xfb, 0xa4,
	0xef, 0xe6, 0xbb, 0x56, 0xb3, 0x3a, 0xf6, 0xa0, 0xbe, 0x98, 0xdb, 0x6c, 0x90, 0x1b, 0x68, 0x97,
	0x64, 0x8c, 0x13, 0x7b, 0xd7, 0xbe, 0xff, 0xc2, 0x76, 0xbf, 0xb6, 0x56, 0x32, 0x5d, 0x80, 0x99,
	0x1a, 0x24, 0x56, 0x45, 0x51, 0x0b, 0xd2, 0xfe, 0x57, 0x53, 0x29, 0xe1, 0xe7, 0x60, 0x2a, 0x07,
	0x7f, 0x75, 0x15, 0x1d, 0x6d, 0x1d, 0x16, 0x4a, 0xf0, 0x0c, 0x3a, 0x7a, 0x6a, 0xbb, 0x48, 0x6a,
	0x1e, 0x61, 0x17, 0x49, 0x5d, 0xd0, 0x4e, 0x63, 0xd9, 0x52, 0x3f, 0xcf, 0xc9, 0x47, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0x37, 0x5f, 0xa3, 0xc3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	ReceiveStart(ctx context.Context, in *StartReceiveRequest, opts ...grpc.CallOption) (*StartReceiveResponse, error)
	ReceiveStop(ctx context.Context, in *StopReceiveRequest, opts ...grpc.CallOption) (*StopReceiveResponse, error)
	Play(ctx context.Context, in *StartPlayRequest, opts ...grpc.CallOption) (*StartPlayResponse, error)
	Stop(ctx context.Context, in *StopPlayRequest, opts ...grpc.CallOption) (*StopPlayResponse, error)
	ClearStorage(ctx context.Context, in *ClearStorageRequest, opts ...grpc.CallOption) (*ClearStorageResponse, error)
}

type playerClient struct {
	cc *grpc.ClientConn
}

func NewPlayerClient(cc *grpc.ClientConn) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) ReceiveStart(ctx context.Context, in *StartReceiveRequest, opts ...grpc.CallOption) (*StartReceiveResponse, error) {
	out := new(StartReceiveResponse)
	err := c.cc.Invoke(ctx, "/player.Player/ReceiveStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) ReceiveStop(ctx context.Context, in *StopReceiveRequest, opts ...grpc.CallOption) (*StopReceiveResponse, error) {
	out := new(StopReceiveResponse)
	err := c.cc.Invoke(ctx, "/player.Player/ReceiveStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Play(ctx context.Context, in *StartPlayRequest, opts ...grpc.CallOption) (*StartPlayResponse, error) {
	out := new(StartPlayResponse)
	err := c.cc.Invoke(ctx, "/player.Player/Play", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Stop(ctx context.Context, in *StopPlayRequest, opts ...grpc.CallOption) (*StopPlayResponse, error) {
	out := new(StopPlayResponse)
	err := c.cc.Invoke(ctx, "/player.Player/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) ClearStorage(ctx context.Context, in *ClearStorageRequest, opts ...grpc.CallOption) (*ClearStorageResponse, error) {
	out := new(ClearStorageResponse)
	err := c.cc.Invoke(ctx, "/player.Player/ClearStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	ReceiveStart(context.Context, *StartReceiveRequest) (*StartReceiveResponse, error)
	ReceiveStop(context.Context, *StopReceiveRequest) (*StopReceiveResponse, error)
	Play(context.Context, *StartPlayRequest) (*StartPlayResponse, error)
	Stop(context.Context, *StopPlayRequest) (*StopPlayResponse, error)
	ClearStorage(context.Context, *ClearStorageRequest) (*ClearStorageResponse, error)
}

// UnimplementedPlayerServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerServer struct {
}

func (*UnimplementedPlayerServer) ReceiveStart(ctx context.Context, req *StartReceiveRequest) (*StartReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveStart not implemented")
}
func (*UnimplementedPlayerServer) ReceiveStop(ctx context.Context, req *StopReceiveRequest) (*StopReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveStop not implemented")
}
func (*UnimplementedPlayerServer) Play(ctx context.Context, req *StartPlayRequest) (*StartPlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Play not implemented")
}
func (*UnimplementedPlayerServer) Stop(ctx context.Context, req *StopPlayRequest) (*StopPlayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedPlayerServer) ClearStorage(ctx context.Context, req *ClearStorageRequest) (*ClearStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearStorage not implemented")
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_ReceiveStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).ReceiveStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/ReceiveStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).ReceiveStart(ctx, req.(*StartReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_ReceiveStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).ReceiveStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/ReceiveStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).ReceiveStop(ctx, req.(*StopReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Play",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Play(ctx, req.(*StartPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Stop(ctx, req.(*StopPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_ClearStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).ClearStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/player.Player/ClearStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).ClearStorage(ctx, req.(*ClearStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "player.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveStart",
			Handler:    _Player_ReceiveStart_Handler,
		},
		{
			MethodName: "ReceiveStop",
			Handler:    _Player_ReceiveStop_Handler,
		},
		{
			MethodName: "Play",
			Handler:    _Player_Play_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Player_Stop_Handler,
		},
		{
			MethodName: "ClearStorage",
			Handler:    _Player_ClearStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}
