// Code generated by protoc-gen-go. DO NOT EDIT.
// source: media.proto

package media

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartReceiveRequest struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Channels             uint32   `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	Rate                 uint32   `protobuf:"varint,4,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReceiveRequest) Reset()         { *m = StartReceiveRequest{} }
func (m *StartReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*StartReceiveRequest) ProtoMessage()    {}
func (*StartReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb54b56db72a97, []int{0}
}

func (m *StartReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReceiveRequest.Unmarshal(m, b)
}
func (m *StartReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReceiveRequest.Marshal(b, m, deterministic)
}
func (m *StartReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReceiveRequest.Merge(m, src)
}
func (m *StartReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_StartReceiveRequest.Size(m)
}
func (m *StartReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartReceiveRequest proto.InternalMessageInfo

func (m *StartReceiveRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *StartReceiveRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *StartReceiveRequest) GetChannels() uint32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

func (m *StartReceiveRequest) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type StartReceiveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReceiveResponse) Reset()         { *m = StartReceiveResponse{} }
func (m *StartReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*StartReceiveResponse) ProtoMessage()    {}
func (*StartReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb54b56db72a97, []int{1}
}

func (m *StartReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReceiveResponse.Unmarshal(m, b)
}
func (m *StartReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReceiveResponse.Marshal(b, m, deterministic)
}
func (m *StartReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReceiveResponse.Merge(m, src)
}
func (m *StartReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_StartReceiveResponse.Size(m)
}
func (m *StartReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartReceiveResponse proto.InternalMessageInfo

type StopReceiveRequest struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReceiveRequest) Reset()         { *m = StopReceiveRequest{} }
func (m *StopReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*StopReceiveRequest) ProtoMessage()    {}
func (*StopReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb54b56db72a97, []int{2}
}

func (m *StopReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReceiveRequest.Unmarshal(m, b)
}
func (m *StopReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReceiveRequest.Marshal(b, m, deterministic)
}
func (m *StopReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReceiveRequest.Merge(m, src)
}
func (m *StopReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_StopReceiveRequest.Size(m)
}
func (m *StopReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopReceiveRequest proto.InternalMessageInfo

func (m *StopReceiveRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type StopReceiveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReceiveResponse) Reset()         { *m = StopReceiveResponse{} }
func (m *StopReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*StopReceiveResponse) ProtoMessage()    {}
func (*StopReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb54b56db72a97, []int{3}
}

func (m *StopReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReceiveResponse.Unmarshal(m, b)
}
func (m *StopReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReceiveResponse.Marshal(b, m, deterministic)
}
func (m *StopReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReceiveResponse.Merge(m, src)
}
func (m *StopReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_StopReceiveResponse.Size(m)
}
func (m *StopReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopReceiveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartReceiveRequest)(nil), "media.StartReceiveRequest")
	proto.RegisterType((*StartReceiveResponse)(nil), "media.StartReceiveResponse")
	proto.RegisterType((*StopReceiveRequest)(nil), "media.StopReceiveRequest")
	proto.RegisterType((*StopReceiveResponse)(nil), "media.StopReceiveResponse")
}

func init() { proto.RegisterFile("media.proto", fileDescriptor_07eb54b56db72a97) }

var fileDescriptor_07eb54b56db72a97 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4d, 0x4d, 0xc9,
	0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x2a, 0xb9, 0x84, 0x83,
	0x4b, 0x12, 0x8b, 0x4a, 0x82, 0x52, 0x93, 0x53, 0x33, 0xcb, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x0a, 0xf2, 0x8b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x21, 0x39, 0x2e, 0xae, 0x94, 0xd4, 0xb2, 0xcc, 0xe4, 0x54, 0xbf, 0xc4, 0xdc,
	0x54, 0x09, 0x26, 0xb0, 0x0c, 0x92, 0x88, 0x90, 0x14, 0x17, 0x47, 0x72, 0x46, 0x62, 0x5e, 0x5e,
	0x6a, 0x4e, 0xb1, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x9c, 0x0f, 0x32, 0xaf, 0x28, 0xb1,
	0x24, 0x55, 0x82, 0x05, 0x2c, 0x0e, 0x66, 0x2b, 0x89, 0x71, 0x89, 0xa0, 0x5a, 0x5d, 0x5c, 0x90,
	0x9f, 0x57, 0x9c, 0xaa, 0xa4, 0xc1, 0x25, 0x14, 0x5c, 0x92, 0x5f, 0x40, 0xd8, 0x45, 0x4a, 0xa2,
	0x20, 0xc7, 0x23, 0xa9, 0x84, 0x18, 0x60, 0x34, 0x8b, 0x91, 0x8b, 0xd5, 0x17, 0xe4, 0x3b, 0x21,
	0x4f, 0x2e, 0x1e, 0x64, 0x2b, 0x84, 0xa4, 0xf4, 0x20, 0x41, 0x80, 0xc5, 0xcb, 0x52, 0xd2, 0x58,
	0xe5, 0xa0, 0x6e, 0x62, 0x10, 0x72, 0xe3, 0xe2, 0x46, 0xb2, 0x4b, 0x48, 0x12, 0xae, 0x1a, 0xdd,
	0xa5, 0x52, 0x52, 0xd8, 0xa4, 0x60, 0xe6, 0x24, 0xb1, 0x81, 0x83, 0xdf, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x7f, 0x79, 0x29, 0xa9, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MediaClient is the client API for Media service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MediaClient interface {
	StartReceive(ctx context.Context, in *StartReceiveRequest, opts ...grpc.CallOption) (*StartReceiveResponse, error)
	StopReceive(ctx context.Context, in *StopReceiveRequest, opts ...grpc.CallOption) (*StopReceiveResponse, error)
}

type mediaClient struct {
	cc *grpc.ClientConn
}

func NewMediaClient(cc *grpc.ClientConn) MediaClient {
	return &mediaClient{cc}
}

func (c *mediaClient) StartReceive(ctx context.Context, in *StartReceiveRequest, opts ...grpc.CallOption) (*StartReceiveResponse, error) {
	out := new(StartReceiveResponse)
	err := c.cc.Invoke(ctx, "/media.Media/StartReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaClient) StopReceive(ctx context.Context, in *StopReceiveRequest, opts ...grpc.CallOption) (*StopReceiveResponse, error) {
	out := new(StopReceiveResponse)
	err := c.cc.Invoke(ctx, "/media.Media/StopReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServer is the server API for Media service.
type MediaServer interface {
	StartReceive(context.Context, *StartReceiveRequest) (*StartReceiveResponse, error)
	StopReceive(context.Context, *StopReceiveRequest) (*StopReceiveResponse, error)
}

// UnimplementedMediaServer can be embedded to have forward compatible implementations.
type UnimplementedMediaServer struct {
}

func (*UnimplementedMediaServer) StartReceive(ctx context.Context, req *StartReceiveRequest) (*StartReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartReceive not implemented")
}
func (*UnimplementedMediaServer) StopReceive(ctx context.Context, req *StopReceiveRequest) (*StopReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopReceive not implemented")
}

func RegisterMediaServer(s *grpc.Server, srv MediaServer) {
	s.RegisterService(&_Media_serviceDesc, srv)
}

func _Media_StartReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServer).StartReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.Media/StartReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServer).StartReceive(ctx, req.(*StartReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Media_StopReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServer).StopReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/media.Media/StopReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServer).StopReceive(ctx, req.(*StopReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Media_serviceDesc = grpc.ServiceDesc{
	ServiceName: "media.Media",
	HandlerType: (*MediaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartReceive",
			Handler:    _Media_StartReceive_Handler,
		},
		{
			MethodName: "StopReceive",
			Handler:    _Media_StopReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "media.proto",
}
